# Generated by Django 5.0.6 on 2025-08-23 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pracownicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czy_wlasny_transport', models.BooleanField(default=False)),
                ('czy_wymagane_dzwiganie', models.BooleanField(default=False)),
                ('czy_wymagane_ukladanie_kwiatow', models.BooleanField(default=False)),
                ('czy_wymagane_prawo_jazdy', models.CharField(blank=True, choices=[('B', 'Kategoria B'), ('C', 'Kategoria C')], max_length=1, null=True)),
                ('data_pracy', models.DateField()),
                ('stawka', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stawka_dzienna_czy_godzinowa', models.CharField(choices=[('dzienna', 'Dzienna'), ('godzinowa', 'Godzinowa')], max_length=10)),
                ('minimalny_czas_pracy', models.PositiveIntegerField()),
                ('szczegoly', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Florysta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('lokalizacja_miasto', models.CharField(max_length=50)),
                ('lokalizacja_wojewodztwo', models.CharField(blank=True, choices=[('dolnośląskie', 'Dolnośląskie'), ('kujawsko-pomorskie', 'Kujawsko-Pomorskie'), ('lubelskie', 'Lubelskie'), ('lubuskie', 'Lubuskie'), ('łódzkie', 'Łódzkie'), ('małopolskie', 'Małopolskie'), ('mazowieckie', 'Mazowieckie'), ('opolskie', 'Opolskie'), ('podkarpackie', 'Podkarpackie'), ('podlaskie', 'Podlaskie'), ('pomorskie', 'Pomorskie'), ('śląskie', 'Śląskie'), ('świętokrzyskie', 'Świętokrzyskie'), ('warmińsko-mazurskie', 'Warmińsko-Mazurskie'), ('wielkopolskie', 'Wielkopolskie'), ('zachodniopomorskie', 'Zachodniopomorskie')], max_length=50, null=True)),
                ('lokalizacja_kraj', models.CharField(default='Polska', max_length=50)),
                ('czy_pracownia', models.BooleanField(default=False)),
                ('czy_freelancuje', models.BooleanField(default=False)),
                ('czy_prawo_jazdy_b', models.BooleanField(default=False)),
                ('czy_prawo_jazdy_c', models.BooleanField(default=False)),
                ('czy_uklada_kwiaty', models.BooleanField(default=True)),
                ('czy_moze_dzwigac', models.BooleanField(default=False)),
                ('czy_pracuje_na_wysokosci', models.BooleanField(default=False)),
                ('czy_ma_auto', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pracownia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('lokalizacja_miasto', models.CharField(max_length=50)),
                ('lokalizacja_wojewodztwo', models.CharField(max_length=50)),
                ('lokalizacja_kraj', models.CharField(default='Polska', max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pracownie', to='florance.florysta')),
            ],
        ),
        migrations.CreateModel(
            name='Kandydat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wybrany', models.BooleanField(default=False)),
                ('data_wyboru', models.DateTimeField(blank=True, null=True)),
                ('florysta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='florance.florysta')),
                ('pracownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='florance.pracownicy')),
            ],
        ),
        migrations.CreateModel(
            name='Realizacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_eventu', models.CharField(max_length=100)),
                ('miejsce', models.CharField(max_length=255)),
                ('data_rozpoczecia', models.DateTimeField()),
                ('data_zakonczenia', models.DateTimeField()),
                ('opis', models.TextField()),
                ('pracownia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='florance.pracownia')),
            ],
        ),
        migrations.AddField(
            model_name='pracownicy',
            name='realizacja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='florance.realizacja'),
        ),
        migrations.CreateModel(
            name='Umiejetnosci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umiejetnosc', models.CharField(max_length=50)),
                ('wartosc', models.BooleanField(default=False)),
                ('florysta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='florance.florysta')),
            ],
        ),
    ]
