# Generated by Django 5.0.6 on 2025-09-21 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kandydat',
            name='data_wyboru',
        ),
        migrations.RemoveField(
            model_name='kandydat',
            name='pracownik',
        ),
        migrations.AddField(
            model_name='kandydat',
            name='stanowisko',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='kandydaci', to='florance.pracownicy'),
            preserve_default=False,
        ),
    ]
