# Generated by Django 5.0.6 on 2025-12-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florance', '0002_remove_kandydat_data_wyboru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kandydat',
            name='wybrany',
        ),
        migrations.AddField(
            model_name='kandydat',
            name='status',
            field=models.CharField(choices=[('oczekuje', 'Oczekuje'), ('wybrany', 'Wybrany'), ('odrzucony', 'Odrzucony')], default='oczekuje', max_length=20),
        ),
        migrations.AddField(
            model_name='kandydat',
            name='wiadomosc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
