# Generated by Django 5.0.6 on 2026-01-03 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florance', '0003_remove_kandydat_wybrany_kandydat_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pracownicy',
            name='assigned_florysta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='przypisane_stanowiska', to='florance.florysta'),
        ),
        migrations.AddField(
            model_name='pracownicy',
            name='assigned_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pracownicy',
            name='assigned_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
