# Generated by Django 5.0.6 on 2026-01-04 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florance', '0004_pracownicy_assigned_florysta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kandydat',
            name='stanowisko',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kandydatury', to='florance.pracownicy'),
        ),
    ]
