# Generated by Django 5.0.6 on 2026-01-04 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florance', '0005_alter_kandydat_stanowisko'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kandydat',
            name='florysta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kandydatury', to='florance.florysta'),
        ),
        migrations.AlterField(
            model_name='kandydat',
            name='stanowisko',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kandydaci', to='florance.pracownicy'),
        ),
    ]
