# Generated by Django 5.0.6 on 2026-01-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florance', '0006_alter_kandydat_florysta_alter_kandydat_stanowisko'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pracownicy',
            old_name='assigned_florysta',
            new_name='przypisany_florysta',
        ),
        migrations.AddField(
            model_name='pracownicy',
            name='przypisane_imie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pracownicy',
            name='przypisane_nazwisko',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pracownicy',
            name='przypisany_telefon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
