# Generated by Django 5.0.6 on 2026-01-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florance', '0007_rename_assigned_florysta_pracownicy_przypisany_florysta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pracownicy',
            name='status_przypisania',
            field=models.CharField(choices=[('oczekuje', 'Oczekuje na potwierdzenie'), ('zaakceptowane', 'Zaakceptowane'), ('odrzucone', 'Odrzucone')], default='oczekuje', max_length=20),
        ),
    ]
