# Generated by Django 5.0.6 on 2026-01-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florance', '0008_pracownicy_status_przypisania'),
    ]

    operations = [
        migrations.AddField(
            model_name='florysta',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
