# Generated by Django 5.0.6 on 2026-01-21 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florance', '0009_florysta_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealizacjaPlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plik', models.FileField(upload_to='realizacje/')),
                ('nazwa', models.CharField(blank=True, max_length=255)),
                ('dodano', models.DateTimeField(auto_now_add=True)),
                ('realizacja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pliki', to='florance.realizacja')),
            ],
        ),
    ]
