# Generated by Django 5.0.6 on 2026-01-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florance', '0010_realizacjaplik'),
    ]

    operations = [
        migrations.AddField(
            model_name='realizacja',
            name='notatki_prywatne',
            field=models.TextField(blank=True),
        ),
    ]
