# Generated by Django 5.0.6 on 2026-01-23 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florance', '0011_realizacja_notatki_prywatne'),
    ]

    operations = [
        migrations.CreateModel(
            name='KomentarzStanowiska',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='florance.florysta')),
                ('stanowisko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentarze', to='florance.pracownicy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
