# Generated by Django 5.0.6 on 2026-02-27 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florance', '0013_powiadomienie'),
    ]

    operations = [
        migrations.AddField(
            model_name='komentarzstanowiska',
            name='typ',
            field=models.CharField(choices=[('owner', 'Prywatny dla ownera'), ('worker', 'Tylko dla konkretnego pracownika'), ('all', 'Dla wszystkich pracowników realizacji')], default='owner', max_length=10),
        ),
        migrations.AddField(
            model_name='komentarzstanowiska',
            name='widoczny_dla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='komentarze_prywatne', to='florance.florysta'),
        ),
        migrations.AddField(
            model_name='realizacjaplik',
            name='widoczny_dla',
            field=models.ManyToManyField(blank=True, related_name='udostepnione_pliki', to='florance.florysta'),
        ),
    ]
