# Generated by Django 5.0.6 on 2026-04-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florance', '0014_komentarzstanowiska_typ_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realizacjaplik',
            name='widoczny_dla',
        ),
        migrations.AddField(
            model_name='realizacjaplik',
            name='widoczne_dla_stanowisk',
            field=models.ManyToManyField(blank=True, related_name='dostepne_pliki', to='florance.pracownicy'),
        ),
    ]
