# Generated by Django 5.0.6 on 2026-04-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('florance', '0015_remove_realizacjaplik_widoczny_dla_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realizacjaplik',
            name='widoczne_dla_stanowisk',
        ),
        migrations.AddField(
            model_name='realizacjaplik',
            name='widoczny_dla',
            field=models.ManyToManyField(blank=True, related_name='udostepnione_pliki', to='florance.florysta'),
        ),
    ]
